stages:
  - build
  - docker
  - deploy
cache:
  key:
    files:
      - frontend/package-lock.json
  paths:
    - frontend/.npm/
variables:
  IMAGE_FRONT: "$CI_REGISTRY_IMAGE/frontend"
# -----------------------------
# BUILD ANGULAR 
# -----------------------------
build_app:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend 
    - npm ci --cache .npm --prefer-offline
    - npm run build -- --configuration production
  artifacts:
    expire_in: 7d
    paths:
      - frontend/dist/
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'

# -----------------------------
# DOCKER BUILD 
# -----------------------------
build_image:
  stage: docker
  image: docker:27
  services:
    - name: docker:27-dind
      command: ["--tls=false"]
  needs:
    - build_app
      artifacts :true
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker pull "$IMAGE_FRONT:latest" || true
    - docker build --cache-from "$IMAGE_FRONT:latest" -t "$IMAGE_FRONT:$CI_COMMIT_SHORT_SHA" frontend/
    - docker push "$IMAGE_FRONT:$CI_COMMIT_SHORT_SHA"

    - docker tag "$IMAGE_FRONT:$CI_COMMIT_SHORT_SHA" "$IMAGE_FRONT:latest"

    - docker push "$IMAGE_FRONT:latest"
# -----------------------------
# DEPLOY STAGING
# -----------------------------
deploy :
  stage : deploy
  script:
    - echo  " deploying ... "
