workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - when: never
stages:
  - test
  - package
  - docker
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  IMAGE_BACK: "$CI_REGISTRY_IMAGE/backend"


cache:
  key :
    files  :
      - backend/pom.xml
  paths:
    - .m2/repository

# -------------------------
# TEST
# -------------------------
test:
  image: maven:3.9.6-eclipse-temurin-17
  stage: test
  script:
    - mvn -f backend/pom.xml clean verify -Dspring.profiles.active=test


# -------------------------
# BUILD JAR
# -------------------------
package:
  image: maven:3.9.6-eclipse-temurin-17
  stage: package
  script:
    - mvn -f backend/pom.xml clean  package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar

# -------------------------
# DOCKER BUILD
# -------------------------
docker:
  stage: docker
  image: docker:27
  services:
    - name: docker:27-dind
      command: ["--tls=false"]

  needs:
     - job: package
       artifacts : true 
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

  script:
    - docker pull "$IMAGE_BACK:latest" || true
    - docker build --cache-from "$IMAGE_BACK:latest" -t "$IMAGE_BACK:$CI_COMMIT_SHORT_SHA"  backend/
    - docker push "$IMAGE_BACK:$CI_COMMIT_SHORT_SHA"
    - docker tag "$IMAGE_BACK:$CI_COMMIT_SHORT_SHA" "$IMAGE_BACK:latest"
    - docker push "$IMAGE_BACK:latest"

# -------------------------
# DEPLOY DEV (auto)
# -------------------------
deploy_dev:
  stage: deploy
  script:
    - echo "Deploying to DEV server..."

  #rules:
  #  - if: $CI_COMMIT_BRANCH == "develop"
