create table refresh_tokens (
    id bigint generated by default as identity primary key ,
    user_id bigint not null,
    token varchar(255) not null,
    expiry_date timestamp with time zone null,
    creation_date timestamp  with time zone null,
    constraint fk_user_refresh_token foreign key (user_id) references users(id) on delete cascade
);