-- ======================
-- ROLES
-- ======================
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50)
);
-- ======================
-- USERS
-- ======================
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) ,
                       password VARCHAR(255)
);

-- ======================
-- USER_ROLES (ManyToMany)
-- ======================
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),

                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users(id),


                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (role_id)
                                    REFERENCES roles(id)

);

-- ======================
-- DEPARTMENTS
-- ======================
CREATE TABLE departments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             department_name VARCHAR(255)
);

-- ======================
-- SPECIALITIES
-- ======================
CREATE TABLE specialities (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              speciality_name VARCHAR(255),

                              department_id BIGINT NOT NULL,

                              CONSTRAINT fk_speciality_department
                                  FOREIGN KEY (department_id)
                                      REFERENCES departments(id)
);

-- ======================
-- ACADEMIC LEVEL
-- ======================
CREATE TABLE academic_level (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(100),
                                academic_year VARCHAR(20),

                                speciality_id BIGINT,

                                CONSTRAINT fk_level_speciality
                                    FOREIGN KEY (speciality_id)
                                        REFERENCES specialities(id)
);

-- ======================
-- GROUPS
-- ======================
CREATE TABLE groups (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        group_name VARCHAR(100) ,

                        academic_level_id BIGINT ,

                        CONSTRAINT fk_group_level
                            FOREIGN KEY (academic_level_id)
                                REFERENCES academic_level(id)
);

-- ======================
-- SUBJECTS
-- ======================
CREATE TABLE subjects (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          subject_name VARCHAR(255) ,
                          coff DOUBLE
);

-- ======================
-- STUDENTS
-- ======================
CREATE TABLE students (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          matricule VARCHAR(50) ,
                          first_name VARCHAR(100),
                          last_name VARCHAR(100),
                          gender VARCHAR(20),

                          cin VARCHAR(20) ,
                          phone VARCHAR(20),

                          user_id BIGINT UNIQUE,
                          group_id BIGINT NOT NULL,

                          enrollment_date DATE,
                          created_at TIMESTAMP,

                          CONSTRAINT fk_student_user
                              FOREIGN KEY (user_id)
                                  REFERENCES users(id),

                          CONSTRAINT fk_student_group
                              FOREIGN KEY (group_id)
                                  REFERENCES groups(id)
);

-- ======================
-- TEACHERS
-- ======================
CREATE TABLE teachers (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          matricule VARCHAR(50) ,
                          first_name VARCHAR(100),
                          last_name VARCHAR(100),

                          cin VARCHAR(20) ,
                          phone VARCHAR(20),

                          grade VARCHAR(100),
                          hire_date DATE,

                          id_department BIGINT,
                          speciality_id BIGINT,
                          user_id BIGINT ,

                          created_at TIMESTAMP,

                          CONSTRAINT fk_teacher_department
                              FOREIGN KEY (id_department)
                                  REFERENCES departments(id),

                          CONSTRAINT fk_teacher_speciality
                              FOREIGN KEY (speciality_id)
                                  REFERENCES specialities(id),

                          CONSTRAINT fk_teacher_user
                              FOREIGN KEY (user_id)
                                  REFERENCES users(id)
);

-- ======================
-- TEACHING ASSIGNMENT
-- ======================
CREATE TABLE teaching_assignment (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     group_id BIGINT ,
                                     subject_id BIGINT ,
                                     teacher_id BIGINT ,

                                     period VARCHAR(10),

                                     CONSTRAINT fk_assignment_group
                                         FOREIGN KEY (group_id)
                                             REFERENCES groups(id),

                                     CONSTRAINT fk_assignment_subject
                                         FOREIGN KEY (subject_id)
                                             REFERENCES subjects(id),

                                     CONSTRAINT fk_assignment_teacher
                                         FOREIGN KEY (teacher_id)
                                             REFERENCES teachers(id)
);