ALTER TABLE teachers
    ADD COLUMN status VARCHAR(30) DEFAULT 'ACTIVE';

CREATE TABLE IF NOT EXISTS teachers_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    teacher_id BIGINT,
    semester_id BIGINT,
    class_id BIGINT,
    CONSTRAINT uk_teacher_course_semester_class UNIQUE (teacher_id, course_id, semester_id, class_id),
    CONSTRAINT fk_teachers_assignment_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_teachers_assignment_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    CONSTRAINT fk_teachers_assignment_semester FOREIGN KEY (semester_id) REFERENCES semesters(id),
    CONSTRAINT fk_teachers_assignment_class FOREIGN KEY (class_id) REFERENCES classes(id)
);
