CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(120),
    capacity INTEGER,
    building VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS timetable_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    session_type VARCHAR(10) NOT NULL,
    course_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    semester_id BIGINT NOT NULL,
    CONSTRAINT fk_timetable_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_timetable_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    CONSTRAINT fk_timetable_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_timetable_class FOREIGN KEY (class_id) REFERENCES classes(id),
    CONSTRAINT fk_timetable_semester FOREIGN KEY (semester_id) REFERENCES semesters(id)
);

CREATE INDEX idx_timetable_teacher_slot ON timetable_entries (teacher_id, semester_id, day_of_week, start_time, end_time);
CREATE INDEX idx_timetable_room_slot ON timetable_entries (room_id, semester_id, day_of_week, start_time, end_time);
CREATE INDEX idx_timetable_class_slot ON timetable_entries (class_id, semester_id, day_of_week, start_time, end_time);

INSERT INTO rooms (code, name, capacity, building)
SELECT 'A101', 'Amphi A101', 120, 'Main'
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE code = 'A101');

INSERT INTO rooms (code, name, capacity, building)
SELECT 'B204', 'Salle B204', 40, 'Teaching Block'
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE code = 'B204');

INSERT INTO rooms (code, name, capacity, building)
SELECT 'LAB-1', 'Laboratoire 1', 24, 'Labs'
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE code = 'LAB-1');
