ALTER TABLE rooms ADD COLUMN IF NOT EXISTS type VARCHAR(80);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS location VARCHAR(160);

UPDATE rooms
SET name = code
WHERE name IS NULL;

UPDATE rooms
SET type = 'CLASSROOM'
WHERE type IS NULL;
