CREATE TABLE IF NOT EXISTS attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    session_code VARCHAR(16) NOT NULL UNIQUE,
    session_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME,
    status VARCHAR(20) NOT NULL,
    course_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    teacher_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_attendance_session_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_attendance_session_class FOREIGN KEY (class_id) REFERENCES classes(id),
    CONSTRAINT fk_attendance_session_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id)
);

CREATE TABLE IF NOT EXISTS attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    note VARCHAR(255),
    marked_at TIMESTAMP,
    CONSTRAINT fk_attendance_record_session FOREIGN KEY (session_id) REFERENCES attendance_sessions(id),
    CONSTRAINT fk_attendance_record_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT uq_attendance_session_student UNIQUE (session_id, student_id)
);

CREATE INDEX idx_attendance_session_filters ON attendance_sessions (class_id, course_id, session_date);
CREATE INDEX idx_attendance_record_session ON attendance_records (session_id);
