ALTER TABLE exams ADD COLUMN IF NOT EXISTS max_score DOUBLE DEFAULT 20;

ALTER TABLE grades ADD COLUMN IF NOT EXISTS max_score DOUBLE DEFAULT 20;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS comment VARCHAR(1000);
ALTER TABLE grades ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'DRAFT';
ALTER TABLE grades ADD COLUMN IF NOT EXISTS graded_at TIMESTAMP;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
