ALTER TABLE enrollments
    ADD COLUMN payment_plan VARCHAR(50);

CREATE TABLE student_payment_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    enrollment_id BIGINT NOT NULL,
    academic_path VARCHAR(20) NOT NULL,
    payment_plan VARCHAR(50) NOT NULL,
    total_amount DECIMAL(12, 2) NOT NULL,
    total_paid DECIMAL(12, 2) NOT NULL,
    remaining_amount DECIMAL(12, 2) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT uq_student_payment_account_student UNIQUE (student_id),
    CONSTRAINT fk_payment_account_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_payment_account_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(id)
);

CREATE TABLE student_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    payment_account_id BIGINT NOT NULL,
    receipt_number VARCHAR(50) NOT NULL,
    payment_date DATE NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    previous_remaining_amount DECIMAL(12, 2) NOT NULL,
    new_remaining_amount DECIMAL(12, 2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT uq_student_payment_receipt UNIQUE (receipt_number),
    CONSTRAINT fk_payment_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_payment_account FOREIGN KEY (payment_account_id) REFERENCES student_payment_accounts(id)
);
