CREATE TABLE enrollments(
    id BIGINT generated by default as Identity primary key ,
    student_id BIGINT NOT NULL ,
    group_id BIGINT NOT NULL ,
    enrollment_date DATE,

    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id)
            REFERENCES students(id),

    CONSTRAINT fk_enrollment_group
        FOREIGN KEY (group_id)
            REFERENCES groups(id) ,
    CONSTRAINT uq_group_students UNIQUE (student_id , group_id)
)