create table password_reset_tokens
(
    id          bigint generated by default as identity primary key,
    token       varchar(255) not null unique ,
    user_id     bigint       not null,
    expiry_date timestamp with time zone    not null,
    constraint fk_user_reset_token foreign key (user_id) references users (id) on delete cascade
)