spring:
  application:
    name: GestionUniversite
  profiles:
     active: dev


reset :
  token :
    expiration : 900
refresh :
  token :
    expiration : 604800
access :
  token :
    expiration : 900

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
